name: Index Oxide Plugins

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # каждые 30 минут

concurrency:
  group: oxide-plugins-index
  cancel-in-progress: false

jobs:
  index:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # нужно для push
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Run indexer (one-shot)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTINUOUS: "false"
        run: timeout 10m npm start || true

      - name: Commit and push changes if any
        if: always()
        working-directory: .
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add backend/output/oxide_plugins.json backend/output/state.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(index): update plugins index [skip ci]"
            git push
          fi
